-- VDat1-6 Spalten erweitern für vollständige Datetime-Werte
-- NOW() liefert 19 Zeichen: "YYYY-MM-DD HH:MM:SS"

ALTER TABLE antraege MODIFY COLUMN VDat1 VARCHAR(19) DEFAULT NULL;
ALTER TABLE antraege MODIFY COLUMN VDat2 VARCHAR(19) DEFAULT NULL;
ALTER TABLE antraege MODIFY COLUMN VDat3 VARCHAR(19) DEFAULT NULL;
ALTER TABLE antraege MODIFY COLUMN VDat4 VARCHAR(19) DEFAULT NULL;
ALTER TABLE antraege MODIFY COLUMN VDat5 VARCHAR(19) DEFAULT NULL;
ALTER TABLE antraege MODIFY COLUMN VDat6 VARCHAR(19) DEFAULT NULL;
